services:
  redis:
    container_name: redis
    image: redis:${REDIS_VERSION}
    env_file:
      - .envs/redis.env
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - "${REDIS_DATA_HOST}:/data"

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:${RABBITMQ_VERSION}-management
    env_file:
      - .envs/rabbitmq.env
    ports:
      - "${RABBITMQ_PORT}:5672"
      - "${RABBITMQ_MANAGEMENT_PORT}:15672"
    volumes:
      - "${RABBITMQ_DATA_HOST}:/var/lib/rabbitmq"

  mysql:
    container_name: mysql
    image: mysql:${MYSQL_VERSION}
    env_file:
      - .envs/mysql.env
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - "${MYSQL_DATA_HOST}:/var/lib/mysql"

  adminer:
    container_name: adminer
    image: adminer:${ADMINER_VERSION}
    env_file:
      - .envs/adminer.env
    ports:
      - "${ADMINER_PORT}:8080"
    depends_on:
      - mysql

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTICSEARCH_VERSION}
    env_file:
      - .envs/elasticsearch.env
    environment:
      - discovery.type=single-node
    ports:
      - "${ELASTICSEARCH_PORT}:9200"
    volumes:
      - "${ELASTICSEARCH_DATA_HOST}:/usr/share/elasticsearch/data"

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:${KIBANA_VERSION}
    env_file:
      - .envs/kibana.env
    ports:
      - "${KIBANA_PORT}:5601"
    environment:
      ELASTICSEARCH_HOSTS: "http://elasticsearch:9200"
    depends_on:
      - elasticsearch

  fluentd:
    container_name: fluentd
    image: fluent/fluentd:${FLUENTD_VERSION}
    env_file:
      - .envs/fluentd.env
    ports:
      - "${FLUENTD_PORT}:24224"
    volumes:
      - "${FLUENTD_DATA_HOST}:/fluentd/etc"
    depends_on:
      - elasticsearch

  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:${JENKINS_VERSION}
    env_file:
      - .envs/jenkins.env
    ports:
      - "${JENKINS_PORT}:8080"
    volumes:
      - "${JENKINS_DATA_HOST}:/var/jenkins_home"

  grafana:
    container_name: grafana
    image: grafana/grafana:${GRAFANA_VERSION}
    env_file:
      - .envs/grafana.env
    ports:
      - "${GRAFANA_PORT}:3000"
    volumes:
      - "${GRAFANA_DATA_HOST}:/var/lib/grafana"

  cassandra:
    container_name: cassandra
    image: cassandra:${CASSANDRA_VERSION}
    env_file:
      - .envs/cassandra.env
    ports:
      - "${CASSANDRA_PORT}:9042"
    volumes:
      - "${CASSANDRA_DATA_HOST}:/var/lib/cassandra"

  minio:
    container_name: minio
    image: minio/minio:${MINIO_VERSION}
    env_file:
      - .envs/minio.env
    ports:
      - "${MINIO_PORT}:9000"
      - "${MINIO_CONSOLE_PORT}:9001"
    command: server /data --console-address ":9001"
    volumes:
      - "${MINIO_DATA_HOST}:/data"

  sftp:
    container_name: sftp
    image: atmoz/sftp:${SFTP_VERSION}
    env_file:
      - .envs/sftp.env
    ports:
      - "${SFTP_PORT}:22"
    volumes:
      - "${SFTP_DATA_HOST}:/home/your_sftp_user/upload"